// Central place for ALL user-facing UI copy (Uzbek, Latin script).
// CLAUDE.md: keep strings in a single place per app for future i18n (UZ/EN/RU).
// Technical/log messages stay English and do NOT belong here.

import type { DocType, JobStatus, Lang, MaterialType } from 'shared';

/** Shared language display names. 'AUTO' is the auto-detect pseudo-option. */
const langs: Record<Lang | 'AUTO', string> = {
  AUTO: 'Avto-aniqlash',
  UZ: "O'zbek",
  EN: 'Ingliz',
  RU: 'Rus',
};

/** Job status labels. 'UPLOADING' is a client-only pre-submit state. */
const statuses: Record<JobStatus | 'UPLOADING', string> = {
  UPLOADING: 'Yuklanmoqda…',
  QUEUED: 'Navbatda',
  PROCESSING: 'Tarjima qilinmoqda',
  REVIEW: 'Tekshiruvda',
  DONE: 'Tayyor',
  FAILED: 'Xato',
};

const docTypes: Record<DocType, string> = {
  DIPLOMA: 'Diplom',
  TRANSCRIPT: "Akademik ma'lumotnoma",
  CERTIFICATE: 'Sertifikat',
  DISSERTATION: 'Dissertatsiya',
  OTHER: 'Boshqa',
};

const materialTypes: Record<MaterialType, string> = {
  LESSON_PLAN: 'Dars rejasi',
  EXERCISES: 'Mashqlar',
  PRESENTATION: 'Taqdimot',
  READING: "O'qish",
  TEST: 'Test',
  VOCABULARY: "Lug'at",
};

export const uz = {
  common: {
    appName: 'Lingo Bridge',
    loading: 'Yuklanmoqda...',
    copy: 'Nusxa',
    view: "Ko'rish",
    download: 'Yuklab olish',
    serviceEyebrow: 'Xizmat',
    optional: '(ixtiyoriy)',
  },
  langs,
  statuses,
  docTypes,
  materialTypes,
  nav: {
    sectionServices: 'Xizmatlar',
    sectionTranslator: 'Tarjimon',
    sectionAdmin: 'Boshqaruv',
    dashboard: 'Asosiy',
    quickTranslate: 'Tezkor tarjima',
    documentTranslation: 'Hujjat tarjimasi',
    materials: 'Materiallar',
    history: 'Tarix',
    review: 'Tekshirish',
    admin: 'Admin panel',
    toggleTheme: 'Mavzu almashtirish',
    openMenu: 'Menyuni ochish',
    closeMenu: 'Menyuni yopish',
    logout: 'Chiqish',
    login: 'Kirish',
    register: "Ro'yxatdan o'tish",
  },
  footer: {
    rights: 'Barcha huquqlar himoyalangan.',
  },
  login: {
    brandEyebrow: "Til Ko'prigi",
    bridgeWords: ['Salom', 'Hello', 'Привет'],
    servicesLine: 'Hujjat tarjimasi · Tezkor tarjima · AI materiallar',
    title: 'Xush kelibsiz',
    subtitle: "Lingo Bridge'ga kirish",
    emailLabel: 'Email',
    emailPlaceholder: 'siz@misol.uz',
    passwordLabel: 'Parol',
    passwordPlaceholder: '••••••••',
    submit: 'Kirish',
    submitting: 'Kirilmoqda...',
    genericError: 'Kirishda xato yuz berdi',
    noAccount: "Hisobingiz yo'qmi?",
    registerLink: "Ro'yxatdan o'ting",
  },
  register: {
    title: 'Hisob yaratish',
    subtitle: "Lingo Bridge'ga qo'shiling",
    fullNameLabel: "To'liq ism",
    fullNamePlaceholder: 'Ism Familiya',
    emailLabel: 'Email',
    emailPlaceholder: 'siz@misol.uz',
    passwordLabel: 'Parol',
    passwordHint: '(kamida 8 ta belgi)',
    passwordPlaceholder: '••••••••',
    submit: "Ro'yxatdan o'tish",
    submitting: "Ro'yxatdan o'tilmoqda...",
    genericError: "Ro'yxatdan o'tishda xato yuz berdi",
    haveAccount: 'Hisobingiz bormi?',
    loginLink: 'Kirish',
  },
  dashboard: {
    welcomeEyebrow: 'Xush kelibsiz',
    fallbackUser: 'Foydalanuvchi',
    prompt: 'Bugun nima qilmoqchisiz?',
    statTranslations: 'Jami tarjimalar',
    statDocuments: 'Hujjatlar',
    statMaterials: 'Materiallar',
    quickActionsTitle: 'Tezkor amallar',
    actionQuickTranslate: 'Tezkor tarjima',
    actionQuickTranslateDesc: 'Matnni bir lahzada tarjima qiling',
    actionDocuments: 'Hujjat tarjimasi',
    actionDocumentsDesc: 'PDF, DOCX hujjatlarni tarjima qiling',
    actionMaterials: 'Material yaratish',
    actionMaterialsDesc: "AI yordamida o'quv materiallar yarating",
  },
  quickTranslate: {
    title: 'Tezkor tarjima',
    swapTitle: 'Tillarni almashtirish',
    fromLabel: 'Asl til',
    toLabel: 'Tarjima tili',
    charSuffix: 'belgi',
    academicMode: 'Akademik rejim',
    translate: 'Tarjima qilish',
    translating: 'Tarjima qilinmoqda...',
    sourcePlaceholder: 'Tarjima qilinadigan matnni kiriting...',
    resultPlaceholder: "Tarjima bu yerda ko'rinadi...",
    detectedLang: 'Aniqlangan til',
    copy: 'Nusxa',
    listen: 'Tinglash',
    genericError: "Tarjima amalga oshmadi. Qaytadan urinib ko'ring.",
  },
  documentTranslation: {
    title: 'Hujjat tarjimasi',
    dropTitle: 'Hujjatni yuklang',
    dropHint: 'PDF, DOCX, JPG, PNG • Har bir fayl ≤ 20MB',
    chooseFile: 'Fayl tanlash',
    docTypeLabel: 'Hujjat turi',
    fromLabel: 'Asl til',
    toLabel: 'Tarjima tili',
    notarize: 'Notarial tasdiq kerak',
    notarizeChip: '+REVIEW',
    keepFormat: 'Formatni saqlash',
    urgent: 'Shoshilinch',
    submit: 'Buyurtma berish',
    orderLabel: 'Buyurtma:',
    download: 'Yuklab olish',
    genericUploadError: 'Yuklash amalga oshmadi',
    genericDownloadError: "Faylni yuklab olishda xato yuz berdi",
    invalidTypeError: 'Faqat PDF, DOCX, JPG yoki PNG fayllar qabul qilinadi',
    tooLargeError: 'Fayl hajmi 20MB dan oshmasligi kerak',
  },
  materials: {
    title: 'Material yaratish',
    subjectLabel: 'Fan',
    subjectPlaceholder: 'Ingliz tili',
    topicLabel: 'Mavzu',
    topicPlaceholder: "Present Perfect, Lug'at…",
    levelLabel: 'Daraja (CEFR)',
    typeLabel: 'Tur',
    outputLangLabel: 'Natija tili',
    notesLabel: "Qo'shimcha izoh",
    notesPlaceholder: '10 ta gap, kalitlari bilan…',
    generate: 'Material yaratish',
    generating: 'Yaratilmoqda...',
    resultTitle: 'Natija',
    resultPlaceholder: "Natija bu yerda ko'rinadi.",
    genericError: "Yaratish amalga oshmadi. Qaytadan urinib ko'ring.",
  },
  history: {
    eyebrow: 'Faoliyat',
    title: 'Tarix',
    filterAll: 'Hammasi',
    typeLabels: {
      quick: 'Tezkor tarjima',
      material: 'Material',
      document: 'Hujjat',
    },
    headers: ['Sana', 'Tur', 'Tafsilot', 'Holat', 'Amal'],
    empty: 'Tarix mavjud emas.',
    loadError: "Tarixni yuklab bo'lmadi. Sahifani yangilab ko'ring.",
  },
  translatorReview: {
    eyebrow: 'Tarjimon paneli',
    title: 'Tekshiruvdagi buyurtmalar',
    description: 'Notarial tasdiq talab qiluvchi tarjimalarni tekshiring va tasdiqlang.',
    headers: ['Buyurtma ID', 'Tur', 'Til', 'Sana', 'Holat', 'Amal'],
    empty: "Tekshiruv kutayotgan buyurtmalar yo'q.",
    verify: 'Tasdiqlash',
    verifyNote: 'Tarjimon tomonidan tekshirildi',
    verifyError: 'Tasdiqlashda xato yuz berdi',
    loadError: "Buyurtmalarni yuklab bo'lmadi.",
  },
  admin: {
    eyebrow: 'Boshqaruv paneli',
    title: 'Admin panel',
    statUsers: 'Foydalanuvchilar',
    statJobsCompleted: 'Bajarilgan buyurtmalar',
    statQuickTranslations: 'Tezkor tarjimalar',
    statMaterials: 'Materiallar',
    statsError: "Statistikani yuklab bo'lmadi.",
    auditTitle: 'Audit jurnali',
    auditPlaceholder: "[Audit log ma'lumotlari bu yerda ko'rinadi]",
    systemTitle: 'Tizim holati',
    serviceRunning: 'Ishlayapti',
    serviceDown: 'Xato',
    serviceUnknown: "Noma'lum",
    services: ['Redis', 'MinIO', 'doc-worker'],
    apiServer: 'API server',
  },
} as const;
